name: CI-Build check

on:
  pull_request:
    branches: [ "develop" ]
  push:
    branches: [ "develop" ]

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # repository checkout
    - name: Checkout
      uses: actions/checkout@v4

    # JDK 환경 설치
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto' # AWS 최적화 배포판

    - name: application.properties 파일 설정
      run: |
        mkdir -p src/main/resources # 디렉토리 생성(이미 존재해도 괜찮음)
        echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties
    # Gradle 환경 설치
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      env:
        SPRING_PROFILES_ACTIVE: test  # Spring Boot의 활성 프로파일을 "test"로 설정
      run: ./gradlew clean build --stacktrace  # Gradle을 실행하여 빌드 수행
      shell: bash  # Bash 셸에서 실행

    - name: 빌드된 파일 이름 변경하기
      run: mv ./build/libs/*SNAPSHOT.jar ./cicdtest.jar

    - name: SCP로 EC2에 빌드된 파일 전송하기
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: cicdtest.jar
        target: /home/ubuntu
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: Project
        # 업로드할 파일의 경로를 지정 (build/libs에 Project jar 파일을 업로드한다.)
        # 빌드 단계에서 생성된 jar파일
        path: build/libs/Project-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
  
    steps:
    # 2-1. EC2 접속 및 jar 파일 실행
    - name: SSH로 EC2에 접속하기
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          sudo fuser -k -n tcp 8080 || true
          sudo nohup java -jar cicdtest.jar > ./output.log 2>&1 &    

  # dependency-submission:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up JDK 17
  #     uses: actions/setup-java@v4
  #     with:
  #       java-version: '17'
  #       distribution: 'temurin'

  #   - name: Generate and submit dependency graph
  #     uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
